FROM mcr.microsoft.com/cbl-mariner/base/core:2.0.20220921

# I often just want to use dnf `repoquery`, since I know it better
# than tdnf's equivalent functionality.
# So, let's create a container that is the base container + dnf.
# We run dnf once here to ensure the repos' GPG keys are imported.
RUN tdnf install -y dnf && \
    dnf -y repoquery --whatprovides dnf

CMD ["/bin/bash"]